### PR TITLE
LPS-105380_TestClassMissingLiferayUnitTestRuleCheck_20210310_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@ling-alan-huang SF is still flagging `AspectJNewEnvClassLoaderTestRuleTest` even though it has `LiferayUnitTestRule`

**Comment by ling-alan-huang** [comment]
See https://github.com/mtambara/liferay-portal/pull/1044

**Pull request closed without merging**
