### PR TITLE
LPS-110686 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-110686

### CODE REVIEW

**Comment by kyle-miho** [comment]
The bundle that offers its resources to extend to a fragment host will never be in the active state, as it just offers its resources to be extended. I think it might be more thorough if we check if the extended resources are actually available

**Comment by kyle-miho** [comment]
cI:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@kyle-miho For the fragment test, switch the order so that the host bundle is installed before the fragment. We want to test that when a fragment is installed, the corresponding host is refreshed and the fragment becomes resolved. Doing it the other way doesn't actually test anything because the fragment will already be present when the host resolves, resolving the fragment.

**Pull request closed without merging**
