### PR TITLE
Lps 98771

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test:jsf

**Comment by vicnate5** [comment]
@stiemannkj1 @ngriffin7a We ran the JSF tests on this fix, these show the failure in this ticket resolved, but there is still a single test failure, do you know about this one?

**Comment by stiemannkj1** [comment]
@vicnate5, looks like this is an intermittent failure and can be ignored: https://issues.liferay.com/browse/FACES-3461.

**Pull request closed without merging**
