### PR TITLE
Lps 115016

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mtambara I spent a long time clean this up, but I am still far far away from being done.
The codebase is just too messy, we can not take it in like this, it is not going to be maintainable.

I send this back to you to do a stage testing, since I have made a lot of changes already.
Also we need to add a lot more test cases to cover those properties handling and osgi header parsing logic. And maybe other normal fileinstall behaviors too.

I need you to run a jacoco coverage report with those tests. I am not asking for 100%, but at least it can not be too low.
There are too many branches that I have no idea how to touch for far.

And we need to think about those rare features that we don't use at all, for example, the ConfigInstaller takes a xml formatted configuration file. Do we really want to support that?

This ticket has taken too long, commerce can not wait on this much more, but we can not just take the messy code in either. You need to push harder on the testing and cleaning up. I will continue to clean up too. If you want to make any cleanup change, ping me first and send the pull to reduce the chance that we conflict.

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test:bundle

**Comment by mtambara** [comment]
ci:test:lpkg

**Comment by kyle-miho** [comment]
Linux Manual Testing Completed, only issue found
- Only support config, not cfg - warn users that are still using cfg (did not get a warning when using a cfg config file)

Victor has a Windows laptop and will run manual tests from the test plan on it as well

**Comment by vicnate5** [comment]
@kyle-miho that requirement about cfg files is brand new from today, I do not expect it to be implemented yet.

**Comment by vicnate5** [comment]
@mtambara @kyle-miho Manual and Integration tests passed on Windows
Full Test log at https://docs.google.com/spreadsheets/d/1xUiUUp2HiPk1RM5jXk4lMkEtgBisb6m6M0pem1A-K6U/edit?userstoinvite=169342701%40liferay.com&ts=5e2a3128#gid=1459719809&range=P3

**Comment by kyle-miho** [comment]
@mtambara im rerunnning the lpkg test for you since it looked like a connection error occured
ci:test:lpkg

**Comment by mtambara** [comment]
ci:test:lpkg

**Comment by mtambara** [comment]
@shuyangzhou looks like all tests passed

**Comment by shuyangzhou** [comment]
Ok, forwarding here https://github.com/shuyangzhou/liferay-portal/pull/9251, @mtambara please continue on the clean up and test case adding.

**Pull request closed without merging**
