### PR TITLE
LPS-102027 Refresh fragment host on initial install

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
@slnn can you do a startup regression check on this? Thanks!

**Comment by slnn** [comment]
OK, got it and will update test results when I got them.

**Comment by slnn** [comment]
Hi @mtambara 

Here are test results:


Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 0c6a48a | 34628 | 23421.2 | 23535 | 23382 | 23178 | 23797 | 23214
37589 | 23948 | 23533 | 25333 | 23983 | 23183 | 23708
PR | - | 39663 | 24611.2 | 25381 | 23569 | 25338 | 25103 | 23665
38559 | 24609.2 | 25091 | 23991 | 24933 | 23758 | 25273

CPU tracing please see:https://mega.nz/#F!4s9UhKBB!keWCxq56csFfbKDDk0BZAw

Lily

**Pull request closed without merging**
