### PR TITLE
Lps 112051

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
@vicnate5 Can you check these test results? Thanks!

**Comment by vicnate5** [comment]
@mtambara only unique failure here is with the TCK test, hopefully the test is just flaky, will re-run just that one.
https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262804/AXIS_VARIABLE=0,label_exp=!master/consoleText

**Comment by vicnate5** [comment]
ci:test:tck

**Pull request closed without merging**
