### PR TITLE
LPS-68625

### PR DESCRIPTION
**Pull request by holatuwol**
Don't need to retest if it fails, just let me know on Skype.

### CODE REVIEW

**Comment by mtambara** [comment]
ci:stop

**Comment by mtambara** [comment]
ci:retest

**Comment by mtambara** [comment]
ci:retest?

**Comment by holatuwol** [comment]
Ah, problem with Deprecated tag.

ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
@holatuwol Email test!

**Pull request closed without merging**
