### PR TITLE
LPS-84374 Fix unix test in order to check that method can recover from a missing entry and update the cache.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by marianoalvarosaiz** [comment]
Hi @mtambara,
 did you have time to take a look to the PR?
Kind regards.

**Comment by mtambara** [comment]
Hi @marianoalvarosaiz, I haven't had time to look at this issue yet, how high of a priority is it?

**Comment by marianoalvarosaiz** [comment]
Hi @mtambara,
 it doesn't have the highest priority, but we would like to have an answer before the end of this week. Would it be possible?

**Pull request closed without merging**
