### PR TITLE
Lps 104004

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
@slnn can you check for any startup regression? Thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @mtambara 

Here are startup test results, the pull is better than baseline

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | fb40504 | 39842 | 19831.6 | 20044 | 19891 | 19690 | 19318 | 20215
PR | - | 39316 | 18807 | 18797 | 18670 | 18627 | 18447 | 19494


Regards
Lily

**Pull request closed without merging**
