### PR TITLE
Integration test to test DataGuard

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Matthew, DispatchLogDisplayContextTest can reproduce issue

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by mtambara** [comment]
@igorbeslic The test runs fine for me, do you have any portal-ext.properties or system-ext.properties set?

**Comment by igorbeslic** [comment]
Hi @mtambara here are my portal-ext.properties
`session.timeout=30

setup.wizard.enabled=false

terms.of.use.required=false

users.reminder.queries.enabled=false

com.liferay.portal.servlet.filters.cache.CacheFilter=false

locales.enabled=en_US,hr_HR

users.indexer.enabled=false
users.search.with.index=false

com.liferay.portal.upload.UploadServletRequestImpl.max.size=210715200

company.security.strangers.verify=false`
I will try once more - I synced up with latest repo and `ant all`

**Comment by igorbeslic** [comment]
@mtambara just for the test, can you try and execute that integration test two times sequentially...

**Comment by mtambara** [comment]
@igorbeslic It looks like DataGuard is unable to delete DispatchTriggers when their system field is true, so it keeps flagging them as new data that needs to be deleted and loops forever. It looks like your test logic is randomly determining if DispatchTriggers are system or not, could you just make they all false? Or explicitly delete them before the test finishes

**Comment by mtambara** [comment]
No problem, glad I could help!

**Pull request closed without merging**
