### PR TITLE
Lps 76910

### PR DESCRIPTION
**Pull request by lanceji92674957**

### CODE REVIEW

**Comment by lanceji92674957** [comment]
ci:test

**Comment by lanceji92674957** [comment]
ci:retest

**Comment by lanceji92674957** [comment]
ci:retest

**Comment by mtambara** [comment]
@lanceji92674957 Rebase error, please resend

**Comment by lanceji92674957** [comment]
Resent at https://github.com/mtambara/liferay-portal/pull/541

**Pull request closed without merging**
