### PR TITLE
Lps 100598 release

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@slnn can you run a regression according to https://github.com/shuyangzhou/liferay-portal/pull/8249#issuecomment-531355958. If there's still a regression, can you get a profile for the one with the largest regression? Thanks!

**Comment by mtambara** [comment]
@slnn can you run a regression on this pull according to the above conditions? Thanks!

**Comment by slnn** [comment]
OK. got it

**Comment by slnn** [comment]
Hi @mtambara,

The last commit of this pull https://github.com/mtambara/liferay-portal/pull/906/commits/f0219e5b857c936e847da512606b787a91b0edca caused a bad memory issue on login when disable the tagpool both on tomcat and liferay, please see the screenshot of VisualVM:
pr-906-login


I also got thread dump and heap dump for login, please see here:https://mega.nz/#F!7iJiDCgB!xL5DFkhHXLa8NQ5Atcw1_A

Due to an unexpected power outage in the office in the afternoon, I failed to run tests with reverting the last commit.

I will rerun it without the last commit or with a fix tomorrow when I go to office.

Sorry for the Inconvenience!
Lily

**Comment by mtambara** [comment]
@slnn I pushed up a new version, should fix the memory issue

**Comment by slnn** [comment]
Hi @mtambara,

Login still encountered the memory issue with disable the tagpool  both tomcat and liferay, please see the screenshot of VisualVM:
pr-906-2_2019-10-10_11-50-09

Thread dump and heap dump please see here:https://mega.nz/#F!bzJFxQaT!DiK6jQQx_sE5kVfV0uXnog

I run test for Login and Blog without the last commit https://github.com/mtambara/liferay-portal/pull/906/commits/cfde1556d6bb09dac2f8d0a88044d1898e93bff0

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 48115 | 263 | 79.4 |  
PR-906 (disable tag pool both tomcat and liferay jasper) | - | 47062 | 254 | 76 | -2.188506703
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 45388 | 268 | 79.8 |  
PR-906  (enable tag pool both tomcat and liferay jasper) | - | 44762 | 266 | 79.7 | -1.379219177
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 45621 | 270 | 798 |  
PR-906  (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 44752 | 264 | 78.1 | -1.904824533

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 15314 | 55 | 136 |  
PR-906 (disable tag pool both tomcat and liferay jasper) | - | 14910 | 315 | 334 | -2.63810892
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 15229 | 103 | 179 |  
PR-906  (enable tag pool both tomcat and liferay jasper) | - | 14728 | 640 | 476 | -3.289776085
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 15281 | 83.2 | 161 | 
PR-906  (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 14815 | 377 | 370 | -3.049538643

CPU tracing for Blog with enable the tagpool both tomcat and liferay please see here:https://mega.nz/#F!emAV1QCZ!0d1VfGKUeFTEz4aJ2DpAkw


Regards
Lily

**Comment by mtambara** [comment]
@slnn I think I've fixed the memory issue, if you still see it then I just need the heap dump and visualvm image. If there's no memory issue, then please run the normal regression check. Thanks!

**Comment by slnn** [comment]
Hi @mtambara 

Here are test results on Login and Blog, this pull is better than previous pulls, the largest drop(only 1.9%) appeared in Login with enable the tagpool both tomcat and liferay.

Upload the cpu tracing for Login with enable the tagpool both tomcat and liferay, please see here:https://mega.nz/#F!avAi0CDQ!4l8D16ZuWuIE-2eah2gaNg

Note: the prefix like "profile-baseline-enable-tagpool-both-tomcat-and-liferay-login-*" is baseline and "profile-test-pr-906-3-enable-tagpool-both-tomcat-and-liferay-login-" is this pull.
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 48115 | 263 | 79.4 |  
PR-906-3 (disable tag pool both tomcat and liferay jasper) | - | 47587 | 259 | 77.5 | -1.097370882
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 45388 | 268 | 79.8 |  
PR-906-3  (enable tag pool both tomcat and liferay jasper) | - | 44525 | 266 | 80.1 | -1.901383626
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 45621 | 270 | 798 |  
PR-906-3  (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 45625 | 262 | 78.3 | 0.00876789198

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 15314 | 55 | 136 |  
PR-906-3 (disable tag pool both tomcat and liferay jasper) | - | 15244 | 81 | 166 | -0.4570980802
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 15229 | 103 | 179 |  
PR-906-3  (enable tag pool both tomcat and liferay jasper) | - | 15062 | 134 | 208 | -1.096592028
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 15281 | 83.2 | 161 |  
PR-906-3  (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 15061 | 163 | 226 | -1.439696355

**Pull request closed without merging**
