### PR TITLE
LPS-117190 By default Liferay should assume that osgi configuration files are encoded in UTF-8

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @mtambara 

as per https://github.com/shuyangzhou/liferay-portal/pull/9262#issuecomment-660875047 I'm sending the corrected changes.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9275

**Pull request closed without merging**
