### PR TITLE
LPS-78064 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by mtambara** [comment]
It looks like the upgrade is still running too late, we see the SQLGrammarExeception before the upgrade runs. See ticket for details

**Comment by achaparro** [comment]
@mtambara please, see the comments in the ticket

Thanks

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/5790

**Pull request closed without merging**
