### PR TITLE
LPS-105380 Add TestClassMissingLiferayUnitTestRuleCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by mtambara** [comment]
@ling-alan-huang How do I run this locally? It's not showing the missing test rules when I run `ant format-source-all` in portal-impl

**Comment by ling-alan-huang** [comment]
@mtambara We should run `../../../gradlew deploy` in `modules/util/source-formatter` before using `ant format-source-all`.

**Comment by mtambara** [comment]
See https://github.com/ling-alan-huang/liferay-portal/pull/369

**Pull request closed without merging**
