### PR TITLE
LPS-82333

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-82333
https://issues.liferay.com/browse/LPS-79309

Hey Matt,
The problem was due to sites which inherit locales not being updated when the global local list changed.  This is because we store the group locales in a map and only update it when the group locales are explicitly updated or the server is restarted.

This fix makes groups which inherit the locales gather locales from the companyLocaleBag instead, so they are never outdated.

Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:test

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6720

**Pull request closed without merging**
