### PR TITLE
Lps 132032

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@vicnate5, I ran RoleModelListenerTest and confirmed this fixes the issue, is that enough or are there others tests I should check with?

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
@mtambara Going to just run all the integration tests so we can confirm we are clear

**Comment by vicnate5** [comment]
@mtambara This looks good, I don't see any cases of the company errors on shutdown across all the integration tests.

**Pull request closed without merging**
