### PR TITLE
add debug

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:stable

**Comment by mtambara** [comment]
ci:test:stable

**Comment by mtambara** [comment]
@kyle-miho Please watch for the blogs web failure

**Comment by vicnate5** [comment]
@mtambara In case this helps, here is the original ticket: https://issues.liferay.com/browse/LPS-121715

**Comment by mtambara** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@mtambara I quarantined the auto upgrade tests in Brian's origin. Once this is merged to upstream I would rebase this branch and revert https://github.com/brianchandotcom/liferay-portal/commit/033b8ff7f8ee5bc3da87af60514f14c5533439c3

**Comment by mtambara** [comment]
ci:test:stable

**Pull request closed without merging**
