### PR TITLE
LRQA-59341 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-59341

### CODE REVIEW

**Comment by kyle-miho** [comment]
Fix tested locally:

> Task :apps:trash:trash-test:testIntegration

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest STANDARD_OUT
    Loading jar:file:/home/kyle/Liferay/bundles/liferay-master-ce/tomcat-9.0.33/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testCompanies STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testCompanies PASSED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testCustomMaxAge STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testCustomMaxAge PASSED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testGroupTrashDisabled STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testGroupTrashDisabled PASSED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testGroups STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testGroups PASSED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testLayoutGroup STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testLayoutGroup PASSED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testRegularGroup STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testRegularGroup PASSED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testStagingGroup STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testStagingGroup PASSED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testStagingLayoutScope STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testStagingLayoutScope PASSED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testStagingTrashDisabled STARTED

com.liferay.trash.service.test.TrashEntryLocalServiceCheckEntriesTest > testStagingTrashDisabled PASSED

> Task :apps:trash:trash-test:stopTestableTomcat

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by mtambara** [comment]
@kyle-miho Why do we need to add setUpPermissionThreadLocal() if the test already uses PermissionCheckerMethodTestRule?

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:stop

**Pull request closed without merging**
