### PR TITLE
Tag cleanup

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@vicnate5 I'm checking on the semantic-versioning failure, can you can the rest for unique failures?

**Comment by vicnate5** [comment]
@mtambara Failures not related

**Pull request closed without merging**
