### PR TITLE
Lps 109539

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test

**Comment by vicnate5** [comment]
@mtambara Looks good.

Some random upgrade failures, probably not related to your pull, but worth noting:
https://testray.liferay.com/reports/production/logs/test-1-18/1583457097072/test-portal-acceptance-pullrequest(master)/2975/functional-upgrade-wildfly160-mariadb102-jdk8/3/0/jenkins-console.txt.gz
https://testray.liferay.com/reports/production/logs/test-1-18/1583457097072/test-portal-acceptance-pullrequest(master)/2975/functional-upgrade-tomcat90-mysql57-jdk8/3/0/jenkins-console.txt.gz

**Pull request closed without merging**
