### PR TITLE
LPS-130748

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by mtambara** [comment]
Hey @hhuijser, a few q's:

1. When I regen with `ant generate-configuration-override-properties`, sf doesn't regen the env properties after. Is that a local issue or do you see that too?
2.  8a9da60 added an equals to the end of each line, I don't think we want that
3. Same commit removed leading spaces between # and `configuration.override`, is that the right format for portal.properties? I can have it regen like that if so

**Comment by hhuijser** [comment]
@mtambara 

1. Is that after deploying latest SF? I had to rewrite the check since regex couldn't handle the large number of properties
2. You can see that's what every property has in `portal.properties`, even the ones commented out... that's how SF knows it's a property (and not a comment), and is able to add the `env`. Is there a specific reason we don't want the `=` for those properties?
3. Yes, if there is a space, we assume it's a comment

**Comment by hhuijser** [comment]
@mtambara 

For 1. I guess it has to do with the fact that SF expects the `=` and removed space (I did that first)

**Comment by mtambara** [comment]
@hhuijser Ahh I see, I'll regen with the equals and removed space then. These are just supposed to exist for the purposes of having something to copy paste into other properties, but if someone's going to use them they'll need an equal anyways, so I think it should be fine

**Comment by mtambara** [comment]
See https://github.com/hhuijser/liferay-portal/pull/5660

**Pull request closed without merging**
