### PR TITLE
Lps 102470

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
@slnn can you check for a startup regression? Thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @mtambara 

Here are test results:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | dc6ae9c | 39849 | 20585 | 20973 | 20569 | 20553 | 20824 | 20006
PR | - | 39584 | 20193.2 | 20824 | 19677 | 19878 | 20670 | 19917

Note: LPS-104378 be reverted locally for Baseline and PR


Regards
Lily

**Pull request closed without merging**
