### PR TITLE
Lps 111696

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@vicnate5 Can you see if this error is happening in upstream testing? I can see it locally in master, looks like it's an error log caused by `ServicePreActionTest`

**Comment by vicnate5** [comment]
@mtambara I don't see this error at head https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/383145/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/

**Comment by vicnate5** [comment]
My above comment is incorrect, the error occurs at head.

Introduced in range https://github.com/liferay/liferay-portal/compare/d677c4fa47e91518f9a1fa898de67b333cf5554c...cbe13b3d9c2b7ffa0e5c173f70e2914bb25f55b7

**Pull request closed without merging**
