### PR TITLE
Lps 100598

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@slnn can you run performance regression with these conditions again https://github.com/shuyangzhou/liferay-portal/pull/8249#issuecomment-531355958

Thanks!

**Comment by slnn** [comment]
Hi @mtambara,

When I ran benchmark test with this pull, many exceptions appeared during the startup of portal, I have tried enable/disable the tag pool for tomcat/liferay, but these exceptions still appeared.

Detailed log please see:https://mega.nz/#!z2h2ha7a!x6E08aBI-dSVcdmr7U6Og5D80jr3mUcRkAm6gX9-Rz8


Regards
Lily

**Comment by mtambara** [comment]
@slnn Ok, I'll look into those. The other two pulls should be safe to test, they don't contain the AtomicReferenceFieldUpdater commit

**Pull request closed without merging**
