### PR TITLE
Lps 100598 api

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
@slnn can you run performance regression with these conditions again https://github.com/shuyangzhou/liferay-portal/pull/8249#issuecomment-531355958

Thanks!

**Comment by slnn** [comment]
OK, got it.

Will test these pulls and update test results when I got them.
https://github.com/mtambara/liferay-portal/pull/895
https://github.com/mtambara/liferay-portal/pull/896
https://github.com/mtambara/liferay-portal/pull/897

**Comment by mtambara** [comment]
Hi @slnn, can you get the regressions asap please? This is a priority issue.

Here's the priority order:
https://github.com/mtambara/liferay-portal/pull/897
https://github.com/mtambara/liferay-portal/pull/896
https://github.com/mtambara/liferay-portal/pull/898

Thanks!

**Comment by slnn** [comment]
Hi @mtambara ,

Here are test results on Login and Blog:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 48115 | 263 | 79.4 |  
PR-897 (disable tag pool both tomcat and liferay jasper) | - | 47857 | 264 | 80 | -0.5362153175
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 45388 | 268 | 79.8 |  
PR-897 (enable tag pool both tomcat and liferay jasper) | - | 45723 | 260 | 77.8 | 0.7380805499
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 45621 | 270 | 798 |  
PR-897 (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 45469 | 256 | 76.1 | -0.3331798952


Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 15314 | 55 | 136 |  
PR-897 (disable tag pool both tomcat and liferay jasper) | - | 15305 | 46.8 | 125 | -0.05876975317
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 15229 | 103 | 179 |  
PR-897 (enable tag pool both tomcat and liferay jasper) | - | 15282 | 64.9 | 144 | 0.3480202246
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 15281 | 83.2 | 161 |  
PR-897 (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 15299 | 71.2 | 152 | 0.1177933381

Regards
Lily

**Comment by mtambara** [comment]
@shuyangzhou

**Pull request closed without merging**
