### PR TITLE
LPS-73789 Application panel not shown on ie11

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hi @mtambara, I have checked this issue and verified that is a CSS problem because of rule specifity. This commit solves the problem.

Could you please review it?

:cat:

:cc @ealonso

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by p2kmgcl** [comment]
ci:retest

**Comment by ealonso** [comment]
sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/51449

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
