### PR TITLE
Osgi reverts test

### PR DESCRIPTION
**Pull request by jpince**
@mtambara I know you and Shuyang are working on this, but Brian asked me to test reverting everything. I cherry-picked some commits from your branch https://github.com/mtambara/liferay-portal/pull/707. Figured you'd be interested in the results.

### CODE REVIEW

**Comment by jpince** [comment]
ci:test

**Comment by mtambara** [comment]
Hey @jpince looks like you missed a commit. I'm also testing here: https://github.com/mtambara/liferay-portal/pull/709

**Comment by mtambara** [comment]
I'm also testing a potential fix here: https://github.com/mtambara/liferay-portal/pull/705

**Comment by jpince** [comment]
@mtambara I found another commit from Ray, https://github.com/liferay/liferay-portal/commit/fd6b1aec34a19d956034226ab0ef16768734986e. Would this also need to be reverted? Or is this ok as part of the rest of the work in LPS-83992?

**Comment by mtambara** [comment]
@jpince I checked with shuyang, that commit is fine

**Comment by jpince** [comment]
ci:reopen

**Comment by mtambara** [comment]
@jpince Looks like lpkg base and independence are failing because of a problem with Oauth, that's unrelated to ray's changes

**Pull request closed without merging**
