### PR TITLE
Lps 104004

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
@slnn can you check for startup regressions? Thanks!

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @mtambara 

Here are test results:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 87c99ca | 38837 | 20087.8 | 19936 | 19770 | 20432 | 19795 | 20506
PR | - | 41195 | 20290.6 | 20281 | 20668 | 19655 | 20451 | 20398


CPU tracings be uploaded in: https://mega.nz/#F!fvwSmAwK!YloEixFoQxzP63RdndEqqA

Regards
Lily

**Pull request closed without merging**
