### PR TITLE
Lps 100598

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @mtambara 

Here are test results on Login and Blog:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 48115 | 263 | 79.4 |  
PR-901 (disable tag pool both tomcat and liferay jasper) | - | 47155 | 257 | 76.6 | -1.995219786
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 45388 | 268 | 79.8 |  
PR-901  (enable tag pool both tomcat and liferay jasper) | - | 44626 | 260 | 77.6 | -1.678857848
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 45621 | 270 | 798 |  
PR-901  (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 44535 | 272 | 81.6 | -2.380482672

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 15314 | 55 | 136 |  
PR-901 (disable tag pool both tomcat and liferay jasper) | - | 15189 | 81.7 | 165 | -0.8162465718
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 15229 | 103 | 179 |  
PR-901  (enable tag pool both tomcat and liferay jasper) | - | 14584 | 554 | 460 | -4.235340469
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 15281 | 83.2 | 161 |  
PR-901  (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 14827 | 289 | 320 | -2.971009751

**Comment by mtambara** [comment]
@slnn can you get a tracing profile for blogs enabling both tomcat and jasper?

**Pull request closed without merging**
