### PR TITLE
Test

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
@jpince

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
@mtambara looked at the tests in https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3601/jenkins-report.html, all of the failures look unrelated.

Do you feel comfortable pushing straight to BChan, since this is blocking FP3 release?

**Comment by mtambara** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63186

**Pull request closed without merging**
