### PR TITLE
Lps 104004

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
ci:test

**Comment by mtambara** [comment]
@slnn Can you do a startup check for this? Thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @mtambara 

Here are startup performance test results:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5
-- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | da7d5e9 | 40721 | 20117.4 | 19599 | 20319 | 20614 | 20403 | 19652
PR | - | 40281 | 19148.2 | 18860 | 18796 | 18989 | 19545 | 19551


Lily

**Pull request closed without merging**
