### PR TITLE
Lps 100598 cleanup debug

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
@slnn, can you please get regressions for this and https://github.com/mtambara/liferay-portal/pull/900 according to https://github.com/shuyangzhou/liferay-portal/pull/8249#issuecomment-531355958. Still a high priority issue

Thanks!

**Comment by mtambara** [comment]
cc @shuyangzhou

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @mtambara ,

Here are test results on Login and Blog:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 48115 | 263 | 79.4 |  
PR-899 (disable tag pool both tomcat and liferay jasper) | - | 46067 | 273 | 82.6 | -4.256468877
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 45388 | 268 | 79.8 |  
PR-899 (enable tag pool both tomcat and liferay jasper) | - | 44394 | 283 | 85.6 | -2.190006169
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 45621 | 270 | 798 |  
PR-899 (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 44397 | 281 | 85 | -2.682974946


Blog:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 15314 | 55 | 136 |  
PR-899 (disable tag pool both tomcat and liferay jasper) | - | 15199 | 90.8 | 176 | -0.750946846
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 15229 | 103 | 179 |  
PR-899 (enable tag pool both tomcat and liferay jasper) | - | 14907 | 199 | 258 | -2.114387025
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 15281 | 83.2 | 161 |  
PR-899 (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 14784 | 458 | 399 | -3.252404947

Regards
Lily

**Comment by mtambara** [comment]
@slnn I pushed up some commits, please retest this and test https://github.com/mtambara/liferay-portal/pull/901 with the same steps. Thanks!

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi @mtambara ,

Here are test results on Login and Blog:
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 48115 | 263 | 79.4 |  
Retest PR-899 (disable tag pool both tomcat and liferay jasper) | - | 46827 | 260 | 77.9 | -2.676919879
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 45388 | 268 | 79.8 |  
Retest PR-899  (enable tag pool both tomcat and liferay jasper) | - | 44742 | 264 | 79.2 | -1.423283687
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 45621 | 270 | 798 |  
Retest PR-899  (enable tagpool in tomcat, disable tagpool in liferay jasper) | - | 44851 | 261 | 78.1 | -1.687819206

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count drop(%)
-- | -- | -- | -- | -- | --
BaseLine (disable tag pool both tomcat and liferay jasper) | 44c1be7 | 15314 | 55 | 136 |  
Retest PR-899 (disable tag pool both tomcat and liferay jasper) | - | 15151 | 90.8 | 169 | -1.06438553
BaseLine (enable tag pool both tomcat and liferay jasper) | 44c1be7 | 15229 | 103 | 179 |  
Retest PR-899  (enable tag pool both tomcat and liferay jasper) | - | 14666 | 557 | 474 | -3.696894084
BaseLine (enable tagpool in tomcat, disable tagpool in liferay jasper) | 44c1be7 | 15281 | 83.2 | 161 |  

I also got cpu tracings for login and uploaded them in here:https://mega.nz/#F!Cyhk1STR!cr_CKk4teot9Nw-tOUXKwA, hope them will be helpful for you.

Tests for https://github.com/mtambara/liferay-portal/pull/901 are running, will update later.

Regards
Lily

**Comment by slnn** [comment]
Update test rests in https://github.com/mtambara/liferay-portal/pull/901

**Pull request closed without merging**
