### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
This is the output of running SF on portal:

```
Remove dependency 'javax.servlet.jsp.jstl' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 19 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.aries.spifly.dynamic.framework.extension' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 20 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.felix.scr' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 24 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.eclipse.equinox.metatype' since it is only used by 1 module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 25 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.osgi.service.http' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 26 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'javax.servlet.jsp-api' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 27 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'javax.servlet.jsp.jstl-api' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 28 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.aries.cdi.extender' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 29 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.aries.cdi.extension.el.jsp' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 30 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.aries.cdi.extension.http' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 31 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.aries.cdi.extra' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 32 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.felix.dependencymanager.shell' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 34 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.felix.eventadmin' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 35 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.felix.gogo.command' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 36 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.apache.felix.gogo.shell' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 37 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'geronimo-annotation_1.3_spec' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 38 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'geronimo-atinject_1.0_spec' since it is only used by 1 module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 39 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'geronimo-interceptor_1.2_spec' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 40 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'geronimo-jcdi_2.0_spec' since it is only used by 1 module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 41 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.eclipse.equinox.console' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 42 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'javax.el' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 43 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'jboss-classfilewriter' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 44 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'jboss-logging' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 45 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'weld-osgi-bundle' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 46 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.osgi.service.cdi' since it is not used by any module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 48 (SourceCheck:GradleRequiredDependenciesCheck)
Remove dependency 'org.osgi.util.function' since it is only used by 1 module: C:/github/liferay-portal/modules/apps/static/required-dependencies/required-dependencies/build.gradle 50 (SourceCheck:GradleRequiredDependenciesCheck)
```

**Comment by ling-alan-huang** [comment]
Hi @mtambara,

Just one question.

See: "count++;" on https://github.com/mtambara/liferay-portal/pull/859/commits/1f6d047b0e10d4043add0c1d6041dafcc03ca5fb#diff-f7c9f0a79c5472e743d0302d8e6233a8R77

Do we need to check if one build.gradle contains more than the same one "dependency"?
some of "dependency" starts with "alloyTaglib", or "antlr", or "compileOnly".

See:
https://github.com/ling-alan-huang/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-taglib/build.gradle#L14-L21
https://github.com/ling-alan-huang/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-expression/build.gradle#L19-L26
https://github.com/ling-alan-huang/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-values-query/build.gradle#L17-L23

Thanks.

**Comment by mtambara** [comment]
Hi @ling-alan-huang 

The goal of this change is to find dependencies being used by one or fewer modules. If one module has multiple declarations of the same dependency, it should only count as a single usage. We also don't care if any given module is using the same dependency multiple times.

**Comment by mtambara** [comment]
Looking at ```_checkDependency``` then, it seems like it will not log the removal message if a single module contains the dependency multiple times, even if it's the only module, correct?  If so, this is not the desired behavior

**Comment by hhuijser** [comment]
@mtambara 

Not correct.

It will log the removal message if either 0 or 1 module is using the dependency (regardless of how many times the module is using it)

**Comment by mtambara** [comment]
Ah ok, my mistake

**Comment by hhuijser** [comment]
Closing, see https://github.com/brianchandotcom/liferay-portal/pull/75407

**Pull request closed without merging**
